# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleBooks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'KRProgressHUD'
  pod 'Hero'

  # Pods for googleBooks

  target 'googleBooksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'googleBooksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
